/* Generated by cbindgen */

#ifndef LIBOPENDRIVE_RUST_H
#define LIBOPENDRIVE_RUST_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct OpenDrive OpenDrive;

typedef struct Road Road;

typedef struct {
    double x;
    double y;
    double z;
    double heading;
} Point;

OpenDrive *opendrive_load(const char *path);

void opendrive_free(OpenDrive *ptr);

uintptr_t opendrive_get_road_count(const OpenDrive *ptr);

const Road *opendrive_get_road(const OpenDrive *ptr, uintptr_t index);

Point road_get_point(const Road *ptr, double s, double t, double h);

#endif /* LIBOPENDRIVE_RUST_H */
